### ISSUE TITLE
Imcompatible with powerline?

### ISSUE THREAD

**Issue by gujiaxi** [Malabarba/rich-minority#10]
I use [powerline](https://github.com/milkypostman/powerline) instead of [smart-mode-line](https://github.com/Malabarba/smart-mode-line).
When I use `(setf rm-blacklist "")` to hide all the minor mode, it does not work.
```
;; powerline
(require 'powerline)
(powerline-default-theme)
;; rich-minority
(require 'rich-minority)
(rich-minority-mode 1)
(setf rm-blacklist "")
```

**Comment by Malabarba** [comment]
It's entirely possible they're incompatible. Rich-minority replaces `'minor-mode-alist` inside `mode-line-modes` with `'(:eval (rm--mode-list-as-string-list))`.

If powerline doesn't respect the values in `mode-line-modes` then they're not going to work together. 

Have you tried activating `rich-minority` *before* powerline?

**Comment by gujiaxi** [comment]
@Malabarba Thanks. I tried activating `rich-minority` first but it still not works.

**Comment by Malabarba** [comment]
Then it does look like they're incompatible, I'm afraid. :-(

**Comment by gujiaxi** [comment]
Thanks anyway.

**Comment by Malabarba** [comment]
np
