### ISSUE TITLE
Unsafe local variables in rich-minority.el

### ISSUE THREAD

**Issue by sten0** [Malabarba/rich-minority#15]
Dear Artur,

When I went to edit rich-minority.el (version 1.0.1) with both Emacs 24.5.1 and 25.1.1 the following warning appeared.
--
The local variables list in rich-minority.el
contains values that may not be safe (*).

Do you want to apply it?  You can type
y  -- to apply the local variables list.
n  -- to ignore the local variables list.
!  -- to apply the local variables list, and permanently mark these
      values (*) as safe (in the future, they will be set automatically.)

  * nameless-current-name : "rm"
--
This was introduced in commit 9e84a66b07700bebb73592fe320c19794c206ce3 , and is also present in HEAD.  I'm in the process of packaging rich-minority and smart-mode-line for Debian and am concerned that this could be an issue that would prevent their inclusion into the archive.

Sincerely,
Nicholas

**Comment by Malabarba** [comment]
Hi Nicolas,

That's normal. This variable is defined in another package of mine
(nameless), which you don't have installed. That's why your Emacs doesn't
know if the variable is safe. You can just answer `n` to ignore the
variable.

Cheers

**Comment by sten0** [comment]
Hi Artur,

Thanks for the confirmation :-)

Cheers,
Nicholas
