### ISSUE TITLE
License of rich-minority

### ISSUE THREAD

**Issue by brandelune** [Malabarba/rich-minority#17]
Hi,

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html

So I wonder if you could consider to change the license of your package to GPL-3+?

Yours,

Jean-Christophe Helary

**Comment by Malabarba** [comment]
I don't mind changing. Would you like to open a PR for that?

**Comment by brandelune** [comment]
I would, but since you have 3 external contributors, it is necessary to have their agreement for the move.

@tarsius @mwfogleman @cpitclaudel would you mind considering the move to GPL3+ ?

**Comment by tarsius** [comment]
No I would not mind. :wink:
Let's move to GPLv3+.

**Comment by mwfogleman** [comment]
I also do not mind; let's move to GPLv3+. Thank you for your work @brandelune.

**Comment by cpitclaudel** [comment]
Happy to move to GPL3+ too. Thanks @brandelune!

**Comment by brandelune** [comment]
Just created a pull request. Let me know if everything is OK.

**Comment by Malabarba** [comment]
Merged. Thanks for your help.

**Comment by wbolster** [comment]
this issue can be closed
