### ISSUE TITLE
Error during redisplay

### ISSUE THREAD

**Issue by ChillarAnand** [Malabarba/rich-minority#9]
Here  is  my config

```
(use-package smart-mode-line
  :config
  (setq sml/no-confirm-load-theme t)
  (rich-minority-mode 1)
  (setq rm-whitelist t)
  (sml/setup)
  (sml/apply-theme 'light))
```

Whenever  a  change is made in any  buffer, it   is throwing this error

```
Error during redisplay: (eval (rm--mode-list-as-string-list)) signaled (wrong-type-argument stringp t) [160 times]
```

Is  there  a way to  prevent   this?

**Comment by Malabarba** [comment]
1. If you're using sml, there's no need to do `(rich-minority-mode 1)`. Sml
will do that for you.
2. You're getting this error because t is not a valid value for
rm-whitelist. You probably just want to leave it as nil.

Cheers

**Comment by ChillarAnand** [comment]
:+1: 

Thank you :-)
